I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/zdialogue/sewer.rpy", line 168, in script
    dm "Ey boss, some random wants to see you."
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
IOError: Couldn't find file 'audio/Sewers.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/zdialogue/sewer.rpy", line 168, in script
    dm "Ey boss, some random wants to see you."
  File "renpy/ast.py", line 674, in execute
    statement_name(getattr(who, "statement_name", "say"))
  File "renpy/ast.py", line 46, in statement_name
    i(name)
  File "renpy/common/000window.rpy", line 114, in _window_auto_callback
    _window_show(auto=True)
  File "renpy/common/000window.rpy", line 69, in _window_show
    renpy.with_statement(trans)
  File "renpy/exports.py", line 1640, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "renpy/display/core.py", line 2517, in do_with
    clear=clear)
  File "renpy/display/core.py", line 2978, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "renpy/display/core.py", line 3660, in interact_core
    renpy.audio.audio.periodic()
  File "renpy/audio/audio.py", line 1106, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "renpy/audio/audio.py", line 1084, in periodic_thread_main
    periodic_pass()
  File "renpy/audio/audio.py", line 1026, in periodic_pass
    c.periodic()
  File "renpy/audio/audio.py", line 492, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "renpy/audio/audio.py", line 74, in load
    rv = renpy.loader.load(fn)
  File "renpy/loader.py", line 766, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'audio/Sewers.mp3'.

